theme = "gruvbox_custom"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
bufferline = "always"
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
# C-e = ":sh wezterm.exe cli split-pane --left --percent 30 -- ~/.config/helix/wezilix.sh %sh{cmd.exe /c echo %%WEZTERM_PANE%%} open zoom > /dev/null"
C-e = ":sh ~/.config/helix/filepicker.fish"

[keys.normal."space"]
x = ":buffer-close"
e = "no_op"
E = "no_op"
o = "add_newline_below"
O = "add_newline_above"
