theme = "gruvbox_custom"

[editor]
line-number = "relative"
shell = ["fish", "-c"]
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save]
focus-lost = true
after-delay.enable = true
after-delay.timeout = 300

[editor.indent-guides]
render = true
character = "▏" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[keys.normal]
C-e = ":sh zellij run -c -f -x 10%% -y 10%% --width 80%% --height 80%% -- bash ~/.config/helix/yazi-picker.sh open"

[keys.normal."space"]
x = ":buffer-close"
e = "no_op"
E = "no_op"
o = "add_newline_below"
O = "add_newline_above"
